main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about_page, name='about'),
    path('documentaries', views.show_content, {'content':'documentaries'} ,name='documentaries'),
    path('short-films', views.show_content, {'content': 'short-films'}, name='short-films'),
    path('anime', views.show_content, {'content': 'anime'}, name='anime'),
]

movie/urls.py
app_name = "movie"

from django.urls import path
from . import views 

urlpatterns = [
    path('list/', views.movie_list, name='list'),
    path('detail/<slug:slug>', views.movie_detail, name='detail'),

]

search/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search, name='search'),
]

serie/urls.py
app_name = "serie"

from django.urls import path
from . import views 

urlpatterns = [
    
    path('list/', views.serie_list, name='list'),
    path('detail/<slug:slug>', views.serie_detail, name='detail'),

    path('season/<int:season_id>', views.load_season_data, name='season_data'),

]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path('register', views.register_user, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    
    path('profile/<int:pk>', views.profile_page, name='profile_page'),
    path('profile/<int:pk>/update_profile', views.update_profile, name='update_profile'),
    path('profile/<int:pk>/update_user_name', views.update_user, name='update_user_name'),
    path('profile/<int:pk>/update_user_pw', views.update_password, name='update_user_pw'),

    path('toggle_watchlist_privacy', views.toggle_watchlist_privacy, name='toggle_watchlist_privacy'),

]

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cinelib</title>
    <!-- CSS and Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<!-- Font Aswesome icon -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet"/>
	
</head>
<body>
	{% csrf_token %}
	
	<header>
		{% include 'navbar.html' %}
	</header>

	<!-- To display the pop-up notification from Django /backend-->
	<div id="global-popup-message" style="position: fixed; z-index: 101; top: 12%; left: 50%; transform: translate(-50%, -15%);">
		{% if messages %}
		{% for message in messages %}
		<div class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'error' %}alert-danger{% else %}alert-warning{% endif %} alert-dismissible fade show mb-2"
			role="alert">
			{{ message }}
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
			{% endfor %}
		</div>
		{% endif %}

		<div id="message-container">
			<!-- display the messages handled by AJAX/fetch api // dynamic placeholder-->
		</div>
		
    </div>

	<div class="container-fluid my-4" style="padding: 0 0.25rem;">

		{% block content %}

		{% block extra_js %}

		{% endblock %}
		{% endblock %}
	</div>

	
	{% include 'footer.html' %}
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
	
	<!-- jQuery / allow AJAX to function -->
	<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>

	<!-- for HTMX operation  // surely need to correct to only work on POST/PUT operation-->
	<script src="https://cdn.jsdelivr.net/npm/htmx.org@2.0.7/dist/htmx.min.js" integrity="sha384-ZBXiYtYQ6hJ2Y0ZNoYuI+Nq5MqWBr+chMrS/RkXpNzQCApHEhOt2aY8EJgqwHLkJ" crossorigin="anonymous"></script>


	<!-- custom js script -->
	<script src="{% static 'js/main.js' %}"></script>

	<!-- pop-up message handling / -->
	<script>
		// Below is only for the message directly coming from django like success login message.
		// But it seem to create a friction with the message coming from 
		document.addEventListener('DOMContentLoaded', function() {
			// Auto dismiss alerts after a few seconds
			setTimeout(function() {
				let alerts = document.querySelectorAll('.alert');
				alerts.forEach(function(alert) {
					// Create a Bootstrap alert instance
					let bsAlert = new bootstrap.Alert(alert);
					// Close it
					bsAlert.close();
				});
			}, 4000); // in milliseconds
		});




	    // Configure HTMX to include CSRF token in all requests
		document.addEventListener('DOMContentLoaded', function() {
			document.body.addEventListener('htmx:configRequest', function(event) {
				event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
			});
		});
	</script>
		
</body>
</html>

templates/footer.html
{% load static %}

<footer class="footer" style="width: 100%; margin: 2rem 0 0 0;">

    <div style="padding: 1rem; margin: auto">

        <div style="display: block; width: fit-content; margin: auto;">
            <p style="margin-bottom: 0;">@2025 <strong>Cinelib7</strong> - (Powered by Django)</p>
            <p> &bull; MIT licence</p>
        </div>

        <div>
            <small>
                This [website, program, service, application, product] uses TMDB and the TMDB APIs but is not endorsed, certified, or otherwise approved by TMDB.
                <img src="{% static 'images/TMDB_logo.svg' %}" class="img-fluid rounded" style="width: 5rem; height: 1rem; margin-bottom: 0.2rem;" alt="Movie poster">
            </small>
        </div>

    </div>
</footer>

templates/navbar.html
{% load static %}

{% block extrahead %}
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
{% endblock %}

<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
	<div class="navbar-layout">

		<!-- LEFT SIDE of navbar -->
		<!-- Home page button -->
		<button class="navbar-toggler" 
				type="button"
				data-bs-toggle="collapse"
				data-bs-target="#mainNavDropMenu"
				aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>


		<a class="navbar-brand mt-2 home-btn" href="{% url 'main:home' %}">
			<h4 class="">Home</h4>
		</a>
		

		<!-- Center-left -->
		<!-- Search content by title / redirect to search page // Search input and submit button -->
		<div class="navbar-search">
			<form class="search-form form-inline" role="search" method="GET" action="{% url 'search:search' %}">
				<input type="text"
					class="form-control search-input"
					placeholder="🔍 search..." 
					name="title" 
					aria-label="Search">
				<button class="submit-btn btn nav-search-btn" type="submit">
					search
				</button>
			</form>
		</div>

		<!-- CENTER of the navbar -->
		<!-- Links of different pages -->
		<div class="collapse navbar-collapse" id="mainNavDropMenu">
			<ul class="navbar-nav ms-lg-1 mt-2">

				<li class="nav-item">
					<a class="nav-link active d-lg-none " href="{% url 'main:home' %}" aria-label="home page link">
						<h5 class="link-btn">Home</h5>
					</a>
				</li>

				{% if request.user.is_authenticated %}
				<li class="nav-item">
					<a class="nav-link active" href="{% url 'user_library:watch_list' request.user.pk %}">
						<h5 class="link-btn">Watchlist</h6>
					</a>
				</li>
				{% endif %}

				<hr class="divider" style="padding: 0; margin: 0;">

				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'movie:list' %}">
						<h5 class="link-btn">Movies</h5>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'serie:list' %}">
						<h5 class="link-btn">TV-shows</h5>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'main:documentaries' %}">
						<h5 class="link-btn">Documentaries</h5>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'main:short-films' %}">
						<h5 class="link-btn">Short-films</h5>
					</a>
				</li>
				<li class="nav-item">
					<a class="nav-link active" aria-current="page" href="{% url 'main:anime' %}">
						<h5 class="link-btn">Anime</h5>
					</a>
				</li>
			</ul>
		</div>

		<div>
			<!-- Right-aligned dropdown menu -->
			<ul class="navbar-nav navbar-profile">
				{% if request.user.is_authenticated %}
				<li class="nav-item dropdown">
					
					<div class="nav-link dropdown-toggle" 
						href="" role="button" 
						data-bs-toggle="dropdown"
						aria-expanded="false">
	
						{% if request.user.profile.profile_picture %}
						<img src="{{ request.user.profile.profile_picture.url }}" class="img-fluid rounded-circle"
							style="width: 2.25rem; height: 2.25rem;" alt="Profile photo">
						{% else %}
						<img src="{% static 'images/default_user_pic.png' %}" class="img-fluid rounded-circle" style="width: 2.25rem; height: 2.25rem;" alt="Profile photo">
						{% endif %}
					</div>
					
					<ul class="dropdown-menu dropdown-menu-end" style="background-color: darkgray; text-align: center;">
						<li>
							<small style="font-weight: 600;">{{ request.user.username.capitalize }}</small>
						</li>
						<hr class="dropdown-divider">
						
						
						<li>
							<a class="dropdown-item" href="{% url 'user:profile_page' request.user.id %}">My profile</a>
						</li>
						<li>
							<a class="dropdown-item" href="{% url 'user:update_profile' request.user.id %}">Edit profile</a>
						</li>
						<li><hr class="dropdown-divider"></li>
						<li>
							<a class="dropdown-item" href="{% url 'user:logout' %}">Log out</a>
						</li>
					</ul>
				</li>
			
				{% else %}
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
						aria-expanded="false">
						<span class="d-none d-xl-inline-block">Sign up / Login</span> 
						<!-- <i class="fa-solid fa-user d-inline-block d-md-none"></i>  -->
						<img src="{% static 'images/user_icon.svg' %}" class="img-fluid rounded-circle d-inline-block d-xl-none" 
						style="width: 1,75rem; height: 1.75rem; background-color: gray; margin-top: 0.2rem;"  alt="user icone">

					</a>
					<ul class="dropdown-menu dropdown-menu-end" style="background-color: darkgray; text-align: center;">
						<li><a class="dropdown-item" href="{% url 'user:login' %}">Login</a></li>
						<li><a class="dropdown-item" href="{% url 'user:register' %}">Register</a></li>
					</ul>
				</li>
				{% endif %}
			</ul>
		</div>

	</div>
</nav>
<div class="navbar-spacer"></div>



<script>
document.addEventListener("show.bs.dropdown", function (event) {
    document.querySelectorAll(".dropdown.show").forEach(dropdown => {
        if (dropdown !== event.target) {
            bootstrap.Dropdown.getInstance(
                dropdown.querySelector('[data-bs-toggle="dropdown"]')
            )?.hide();
        }
    });
});
</script>