comment/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # path('show_comment/<int:pk>/', views.show_comment, name='show_comment'),
    path('create', views.create_comment, name='create'),
    path('delete_comment/<int:pk>/', views.delete_comment, name='delete_comment'),
    path('edit/<int:pk>/', views.edit_comment, name='edit'),

]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('about', views.about_page, name='about'),
    path('documentaries', views.show_content, {'content':'documentaries'} ,name='documentaries'),
    path('short-films', views.show_content, {'content': 'short-films'}, name='short-films'),
    path('anime', views.show_content, {'content': 'anime'}, name='anime'),
]

movie/urls.py
app_name = "movie"

from django.urls import path
from . import views 

urlpatterns = [
    path('list/', views.movie_list, name='list'),
    path('detail/<slug:slug>', views.movie_detail, name='detail'),

]

serie/urls.py
app_name = "serie"

from django.urls import path
from . import views 

urlpatterns = [
    
    path('list/', views.serie_list, name='list'),
    path('detail/<slug:slug>', views.serie_detail, name='detail'),

    path('season/<int:season_id>', views.load_season_data, name='season_data'),

]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'user'

urlpatterns = [
    path('register', views.register_user, name='register'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    
    path('profile/<int:pk>', views.profile_page, name='profile_page'),
    path('profile/<int:pk>/update_profile', views.update_profile, name='update_profile'),
    path('profile/<int:pk>/update_user_name', views.update_user, name='update_user_name'),
    path('profile/<int:pk>/update_user_pw', views.update_password, name='update_user_pw'),

    path('toggle_watchlist_privacy', views.toggle_watchlist_privacy, name='toggle_watchlist_privacy'),

]

user_library/urls.py
app_name = "user_library"

from django.urls import path
from . import views 

urlpatterns = [
    path('like/<str:content_type>/<int:object_id>/', views.toggle_like, name='toggle_like'),
    path('watchlist/<str:content_type>/<int:object_id>/', views.toggle_watchlist, name='toggle_watchlist'),
    path('liked/<int:pk>/liked_content', views.liked_content_view, name='liked_view'),
    path('<int:pk>/watch_list/', views.watch_list_view, name='watch_list'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from datetime import datetime

# Create a Profile models here that inherit from the django built-in User.
class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile", unique=True)
    date_of_birth = models.DateField(blank=True, null=True)
    phone = models.CharField(max_length=15, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    profile_picture = models.ImageField(upload_to='images/profile_pictures/', null=True, blank=True)
    background_picture = models.ImageField(upload_to='images/background_pictures/', null=True, blank=True)
    bio = models.TextField(max_length=2000, blank=True)
    # Time stamp
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    watchlist_private = models.BooleanField(default=True, help_text="Toggle watchlist between private and public")  # User can decide if their watchlist is private or can be publicly viewed

    # Meta
    class Meta:
        db_table = 'profile'
        verbose_name = 'Profile'
        verbose_name_plural = 'Profiles'
        ordering = ['id']


    def __str__(self):
        return self.user.username


    def render_age(self):
        '''Return user's age.'''
        # calculate the age from date of birth to today.
        if self.date_of_birth:
            today = datetime.today().date()
            birthdate = self.date_of_birth

            # check if birthday's date already happened this year or not.
            age = today.year - birthdate.year
            if (today.month < birthdate.month) or (today.month == birthdate.month and today.day < birthdate.day):
                age -= 1
            return age
        else:
            print("No age found ?")
            return None


    def last_update(self):
        ''' display the last time an update was performed in a nicer format'''
        try:
            if self.updated_at:
                now = datetime.now(self.updated_at.tzinfo)
                # get the time difference between now and updated_at
                elapsed_time = now - self.updated_at

                minute = elapsed_time.seconds // 60
                hour = elapsed_time.seconds // 3600
                month = elapsed_time.days // 30

                if month == 1:
                    return f"{month} month ago "
                elif month > 0:
                    return f"{month} months ago "
                elif elapsed_time.days == 1:
                    return f"{elapsed_time.days} day ago"
                elif elapsed_time.days > 0:
                    return f"{elapsed_time.days} days ago"
                elif hour == 1:
                    return f"{hour} hour ago"
                elif hour > 0:
                    return f"{hour} hours ago"
                elif minute == 1:
                    return f"{minute} minute ago"
                elif minute > 0:
                    return f"{minute} minutes ago"
                elif elapsed_time.seconds > 0:
                    return f"less than a minute ago"
                elif elapsed_time.seconds >= 0:
                    return f"Just now"
    
        except Exception as e:
            print("e")
            return "issue with the update"


# create Profile when a new User is created
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()

post_save.connect(create_profile, sender=User)

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User

import time

from .models import Profile
from .forms import RegisterForm, EditProfileForm, UpdateUserForm
from user_library.models import Like
from comment.models import Comment
from movie.models import Movie
from serie.models import Serie


def register_user(request):
    '''User registration page'''
    if request.method == 'GET':
        form = RegisterForm()  # Create an instance of the form
        return render(request, 'user/register.html', {'form': form})  # Render the form to the user.

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # might not need to retrieve the username & pw

            try:
                login(request, user)
                messages.success(request,
                                f"Account successfully created!    Hello, {username}! You are now logged in."
                                f"Click here to complete your profile"
                                )

                return redirect(to='main:home')
            
            except Exception as e:
                print(f"An error occurred:\n\n {e}")
                # raise HttpResponse("An error occurred while trying to register the user.\nPlease refresh the page and try again")
                return redirect(to='user:register')

        else:
            messages.error(request, "It seems some fields entered was not valid, Please check and try again")
            return render(request, 'user/register.html', {'form': form, 'error': 'Form is not valid'})


def login_user(request):
    '''User login view page'''

    if request.method == "GET": # user request to go to the login page url
        return render(request, 'user/login.html', {})

    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            print(f"\n- User '{user.username}' logged in. \n")
            messages.success(request, (f"logged in! Hello {user.username}."))
            return redirect(to='main:home')
        
        else:
            print("\n - User not found OR credentials don't match. \n")
            messages.error(request, ("User and password don't match. Please try again"))
            return redirect(to='user:login')

# log out function
@login_required
def logout_user(request):
    logout(request)
    messages.success(request, ("You are logged out!"))
    return redirect(to='/')


@login_required(login_url= "user:login")
def profile_page(request, pk):
    ''' Returns the profile page of the user_id/pk requested
        At the moment users can visit other user's profile, but this may be changed
    '''
    start_time = time.time()

    if request.user.is_authenticated:
        # fetch the profile being requested
        profile = Profile.objects.get(user=pk)
        like = Like.objects.filter(user=pk)
        # print(f"like: {like}") # debug print

        total_like = like.count()

        # Displaying the comment posted by the user
        comments = Comment.objects.filter(user=pk).order_by('-created_at')

        # load the last 3 Watchlist added by the user
        watchlist_items = profile.user.watchlist.all().order_by('-created_at')[:4] 
        print(f"\nwatchlist_items: {watchlist_items}\n\n") # debug print

        # get the content (movie/serie) related to each comment.
        #  Only poster_image, title and genre needed
        last_watchlist = []
        for item in watchlist_items:
            if item.content_object:
                last_watchlist.append({
                    'object': item.content_object, # retrieve the whole object through foreign key
                    'kind': item.kind,
                    'added_on': item.created_at.strftime("%d %B %Y"),
                    'poster': item.content_object.render_poster,
                    'title': item.content_object.title,
                    'genre': item.content_object.render_genre,
                })
        print(f"\nlast_watchlist: {last_watchlist}\n") # debug print

        # Templates for future fav movies display
        fav_movies = (1, 2, 3)

        # fetch the movies and series that are commented by the user
        comment_content = []
        for comment in comments:

            if comment.content_object:
                comment_content.append({
                    'object': comment.content_object,
                    'kind': comment.kind,
                    'created_at': comment.created_at.strftime("%d %B %Y"),
                    'body': comment.body,
                    'user': comment.user,
                })

        print(f"comment_content: {comment_content}\n") #debug print

        context = {
            'profile': profile,
            'like': like,
            'total_like': total_like,
            'comment_content': comment_content,
            'last_watchlist': last_watchlist,
            'fav_movies': fav_movies
        }

        end_time = time.time()
        elapsed_time = end_time - start_time
        print(f"time: {elapsed_time:.2f} seconds.")

        return render(request, 'user/profile_page.html', context=context)
    
    else:
        messages.error(request, ("You must be logged in to access this page"))
        return redirect(to='user:login')


def update_profile(request, pk):
    ''' User can submit form to edit profile.
        Only the user himself can access this page.
        If someone tries to access another user's profile update page, they will be redirected to their own profile.
        request.user.id must be same as the target profile.user_id OR user.id/pk. 
    '''

    if request.user.is_authenticated and request.user.id != pk:

        print("\n* Unauthorised acces: user tried to access another User_Profile_update_page *\n")
        messages.error(request, ("You are not authorized to acces this page."))
        return redirect(to='user:profile_page', pk=request.user.id)


    elif request.user.is_authenticated and request.user.id == pk:
        # fetch the profile being requested
        profile = Profile.objects.get(user_id=pk)
        if request.method == 'GET':
            form = EditProfileForm(instance=profile)

            return render(request, 'user/edit_profile.html', {'form': form})

        if request.method == 'POST':
            # update the profile with the new information
            form = EditProfileForm(request.POST or None, request.FILES or None, instance=profile)

            if form.is_valid():
                form.save()

                print(f"\n - User '{profile.user.username}' updated their Profile. \n")
                messages.success(request, "Profile updated!")
                return redirect(to=f'user:profile_page', pk=pk) 
            
            else:
                messages.error(request, "Please correct the errors in the form.")
                return render(request, 'user/edit_profile.html', {'form': form})
        
    else:
        messages.error(request, ("You must be logged in to access this page"))
        return redirect(to='user:login')


def update_user(request, pk):
    ''' User can submit form to edit their first_name, last_name and user_name'''

    if request.user.is_authenticated and request.user.id != pk:
        print("\n* Unauthorised acces: user tried to access another User_update_page *\n")
        messages.error(request, ("You are not authorized to acces this page."))
        return redirect(to='user:profile_page', pk=request.user.id)

    elif request.user.is_authenticated and request.user.id == pk:
        # fetch the profile being requested
        current_user = User.objects.get(pk=pk)

        if request.method == 'GET':
            form = UpdateUserForm(instance=current_user)

            return render(request, 'user/edit_user.html', {'form': form})

        if request.method == 'POST':
            # update the profile with the new information
            form = UpdateUserForm(request.POST, instance=current_user)

            if form.is_valid():
                current_user = form.save()

                print("User's credentials were updated.")
                messages.success(request, "your credential was updated!")
                return redirect(to=f'user:profile_page', pk=pk) 
            else:
                messages.error(request, "Please correct the errors in the form.")
                return render(request, 'user/edit_user.html', {'form': form})
        
    else:
        messages.error(request, ("You must be logged in to access this page"))
        return redirect(to='user:login')


def update_password(request, pk):
    ''' User can request to change their password'''

    if request.user.is_authenticated and request.user.id != pk:
        print("\n* Unauthorised acces: user tried to access another User's account setting *\n")
        messages.error(request, ("You are not authorized to acces this page."))
        return redirect(to='user:profile_page', pk=request.user.id)

    elif request.user.is_authenticated and request.user.id == pk:
        # fetch the profile being requested
        user = User.objects.get(pk=pk)

        if request.method == 'GET':
            form = PasswordChangeForm(user=user)
            return render(request, 'user/edit_password.html', {'form': form})

        if request.method == 'POST':

templates/user/profile_page.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<br>
<br>

<div class="container-fluid my-4">
    <div class="custom-wide">
        <div class="row">
            
            
            <!-- Left section of the screen -->
            <aside class="custom-col-1-5 side-wrapper">
                <div></div>
            </aside>
            
            <main class="custom-col-9 main-wrapper">

                <div class="card text-center">

                    <div class="card-header" style="display: flex; justify-content: space-between; margin: 0.2rem; padding: 0.4rem;">
                        <p></p>
                        <h4 style="margin: 0;">{{ profile.user.username.capitalize }}</h4>
                        <p style="margin: 0;"><strong>Member since: </strong>{{ profile.created_at|date:"d M Y" }}</p>
                    </div>
                
                    <!-- Main profile part: image, bio, Fav movies. -->
                    <div class="card-body">
                        <div class="row">
                        
                            <div class="col-2 card-text" style="text-align: left;">
                                <p style="margin-bottom: 0.4rem;"><strong>age: </strong><small>{{ profile.render_age }}</small></p>
                                <!-- <p style="margin-bottom: 0.1rem;"><strong>Member since: </strong><small>{{ profile.created_at|date:"d M Y" }}</small></p> -->
                                <p style="margin-bottom: 0rem;"><strong>Last updated: </strong><small class="text-body-secondary">{{ profile.last_update }}</small></p>
                            </div>

                            <!--  profile picture -->
                            <div class="col-3" style="margin-top: 2px; margin-right: 1rem;">
                                {% if profile.profile_picture %}
                                <img src=" {{ profile.profile_picture.url }} " class="img-fluid rounded" style="width: 200px; height: 200px;" alt="Profile photo">
                                {% else %}
                                <img src="{% static 'images/default_user_pic.png' %}" class="img-fluid rounded" style="margin: 0px 25px; width: 200px; height: 200px;" alt="Profile photo">
                                {% endif %}
                            </div>
                        
                            <div class="col-2">
                                <div style="text-align: left; margin-top: 25px; margin-bottom: 10px;">
                                    <h6 class="card-title" style="margin-bottom: 25px;">{{ profile.bio }}</h6>
                                    <!-- <p class="card-text" style="margin-bottom: 25px;">{{ profile.bio }}</p> -->
                                </div>
                            </div>

                            <div class="col-4" style="align-items: center; margin: 0 auto; border-left: solid rgb(107, 105, 105);">

                                <p>My Favorit movies:</p>

                                <div class="row" style="justify-content: center; padding: 0%; width: 100%;">
                                    <!-- Create and insert top3-10 /favorit Movies of user. -->
                                    <!-- {% for movie in favorite_movies %} -->
                                    <!-- {% endfor %} -->
                                    {% for i in fav_movies %}
                                    <!-- Temporary until real Top movies exist -->
                                    <div class="col-12 col-sm-12 col-md-4 col-lg-4 col-xl-4 col-xxl-4" style="height: fit-content; margin-bottom: 1rem;">
                                        
                                        <div class="media-card h-100 w-100" style="padding: 0%;">
                                            <div class="poster-wrapper" title="{{ movie.render_genre}}">
                                                
                                                <div>
                                                    {% if i.render_poster %}
                                                    <img src="{{ movie.render_poster}}" class="img-fluid rounded" style="" alt="Movie poster">
                                                    {% else %}
                                                    <img src="{% static 'images/default_poster_photo.jpg' %}" class="img-fluid rounded" style="" alt="Profile photo">
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </div>
                            </div>

                        </div>
                    </div>

                    <!--  User's data, content such like watch list, liked movies -->
                    <div class="card-footer text-body-secondary d-flex space-evenly" style="width: 100%;">

                        <div class="d-flex" style="margin-left: 5%; margin-right: 2.5%;">
                            <a href="{% url 'user_library:watch_list' request.user.id %}" class="btn btn-primary" style="background-color: rgb(75, 13, 13); padding-top: 0.5rem; padding-bottom: 0rem; border-color: black;">
                                Watchlist
                            </a>
                            <!-- clickable button to trigger if user's watchlist is private or public -->
                            <div style="margin-left: 2.5rem;">
                                {% if request.user.profile == profile %}
                                {% include "user/partials/toggle_privacy_watchlist.html" %}
                                {% endif %}
                            </div>
                        </div>
                    
                        <div class="d-flex" style="margin-left: 10%; margin-bottom: 0 ;padding-bottom: 0;">
                            {% if like %}
                            <a href="{% url 'user_library:liked_view' request.user.id %}"
                                class="btn btn-secondary"
                                style="background-color: rgb(127, 143, 231); padding-top: 0.5rem; padding-bottom: 0rem">
                                Media Liked
                            </a>
                            {% else %}
                            <a href="#" class="btn btn-secondary" style="background-color: rgb(127, 143, 231);">Media Liked </a>
                            {% endif %}
                            <p style="margin: 0.5rem 0 0 0.5rem;">{{ total_like }} likes</p>
                        </div>
                    
                    </div>
                </div>

                <!--  Last User's activity -->
                <div class="row d-block d-md-flex" style="width: 95%; margin: auto;">

                    <!--  Last comments posted-->
                    <div class="col">
                        <!-- <div class=""> -->
                        
                            <div style="border: solid darkgrey; border-bottom: none; border-top-left-radius: 1em; border-top-right-radius: 1em; margin-top: 10%; padding-bottom: 10%;">
                            
                                <h3 style="margin-top: 2rem; margin-bottom: 1rem; text-align: center;">Last activity:</h3>

                                {% if comment_content %}
                                {% for item in comment_content|slice:"0:3" %}
                                <div class="mb-4">
                                
                                    <div class="card text-center" style="border: solid 2px darkslategray;">

                                        <div class="card-body d-flex">
                                            <p class="card-text" style="width: 95%;">{{ item.body }}</p>
                                        </div>
                                    
                                        <div class="card-footer text-body-secondary d-flex" style="justify-content: space-between;">
                                            <p></p>
                                            <div>
                                                <small>Commented on: {{ item.created_at }}</small>
                                            
                                                {% if item.kind == 'movie' %}
                                                <a href="{% url 'movie:detail' slug=item.object.slug %}" style="text-decoration: none; color: inherit;">
                                                    <span style="font-weight: bold;">| {{ item.object.title|slice:":50" }}</span>
                                                </a>
                                            
                                                {% elif item.kind == 'serie' %}
                                                <a href="{% url 'serie:detail' slug=item.object.slug %}" style="text-decoration: none; color: inherit;">
                                                    <span style="font-weight: bold;">| {{ item.object.title|slice:":50"  }}</span>
                                                </a>
                                                {% endif %}
                                            </div>
                                        
                                            <!-- delete option for Comments if user is owner of comment -->
                                            <div style="margin-top: auto;">
                                                {% if item.user.pk == request.user.pk %}
                                                <a href="{% url 'comment:delete_comment' item.user.pk %}">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                                {% endif %}
                                            </div>
                                        
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                                {% else %}
                                <br>
                                <br>
                                <h4 style="text-align: center; color: antiquewhite;">you have not posted any comments yet.</h4>
                                {% endif %}
                            
                            </div>
                        <!-- </div> -->
                    </div>

                    <!-- Other activities -->
                    <div class="col" style="width: fit-content;">
                        <div style="border: solid darkgrey; border-bottom: none; border-top-left-radius: 1em; border-top-right-radius: 1em; margin-top: 10%; padding-bottom: 10%;">
                            {% if request.user.profile == profile %}
                            <h3 style="margin-top: 2rem; margin-bottom: 5%; text-align: center;">
                                Last added to your watchlist:
                            </h3>
                            {% else %}
                            <h3 style="margin-top: 2rem; margin-bottom: 5%; text-align: center;"
                            >Last added to their watchlist:
                            </h3>
                            {% endif %}
                            
                            <!-- PLace here the last 3 Media liked and Watchlist as 2 boxes and link to these  -->
                            {% if last_watchlist %}
                            <div class="row" style="width: 100%; margin: auto;">
                                {% for item in last_watchlist %}
                                <div class="col-6 col-sm-6 col-md-6 col-lg-6 col-xl-3 col-xxl-3" style="height: 100%; width: auto; margin: auto; align-items: center;">
                                    <div class="media-card h-100 w-100" style="margin: 5% 0 10% 0;">
                                        {% if item.kind == 'movie' %}
                                        <a href="{% url 'movie:detail' slug=item.object.slug %}">
                                            <img src="{{ item.poster }}" title="{{ item.genre}}" alt="watchlist media" class="img-fluid rounded" style="width: 120px; height: 180px;">
                                        </a>
                                        {% elif item.kind == 'serie' %}
                                        <a href="{% url 'serie:detail' slug=item.object.slug %}">
                                            <img src="{{ item.poster }}" title="{{ item.genre}}" alt="watchlist media" class="img-fluid rounded" style="width: 120px; height: 180px;">
                                        </a>
                                        {% endif  %}

                                    </div>
                                
                                </div>
                                {% endfor %}
                            </div>
                            
                            {% endif %}
                        </div>

                        <!-- </div> -->
                    </div>
                </div>

            </main>

            <!-- Right section of the screen -->
            <aside class="custom-col-1-5 side-wrapper">
                <div>
                </div>
            </aside>

        </div>
    </div>
</div>

{% endblock %}

templates/user/register.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="custom-wide">
    <div class="row">

        <!-- Left section of the screen -->
        <aside class="custom-col-1-5 side-wrapper">
            <div></div>
        </aside>

        <main class="custom-col-9 main-wrapper">
            
            <div class="register-card col-12">
                <div class="inner-register-card">

                    <div class="register-form">
                        <div style="text-align: center; margin: 1rem 0;">
                            <h2>Register</h2>
                            <hr style="margin: 8px;">
                        </div>
        
                        <form method="POST" action="{% url 'user:register' %}">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <!-- help text's color set directly in forms.py -->
                            <div style="text-align: center; padding: 4% 0;">
                                <button type="submit" class="btn btn-secondary">
                                    submit
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div style="padding-bottom: 5%;"></div>

        </main>

        <!-- Right section of the screen -->
        <aside class="custom-col-1-5 side-wrapper">
            <div>
            </div>
        </aside>

    </div>
</div>


{% endblock %}